# Ubuntu 14.04 Trusty support
os: linux
dist: trusty
language: c++
compiler:
#  - clang
  - gcc

before_install: 
  - sudo apt-get install git cmake build-essential bison 
  - sudo apt-get install libx11-dev libxcb1-dev 
  - sudo apt-get install libx11-xcb-dev #libx11-xcb1
#  - sudo apt-get install libwayland-dev libmirclient-dev 
  - sudo apt-get install libxkbcommon-dev

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..
  - make

